version: "3.8"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: "3600" # Check for updates every hour
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_DEBUG: true
      WATCHTOWER_LABEL_ENABLE: true
      TZ: ${TZ}
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  #-------------------------------------------------------------------------------------------------#
  autoheal:
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=90
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: willfarrell/autoheal
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
    labels:
      com.centurylinklabs.watchtower.enable: "true"
#-------------------------------------------------------------------------------------------------#
networks:
  internal:
    driver: bridge
