version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: media-stack-prod
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 8324:8324
      - 32410-32414:32410-32414/udp
      - 32469:32469
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=${PLEX_VERSION}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /docker/plex/config:/config
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/media/tv:/tv
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/media/movies:/movies
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/media/music:/music
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    healthcheck:
      test: curl --fail -s http://localhost:32400/web/index.html || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  expressvpn:
    image: misioslav/expressvpn:latest-armhf-bullseye
    container_name: expressvpn
    restart: unless-stopped
    network_mode: media-stack-prod
    ports:
      - 80:80
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - 8989:8989
      - 7878:7878
      - 9696:9696
      - 5055:5055
      - 8787:8787
      - 8191:8191/tcp
    environment:
      - WHITELIST_DNS=${WHITELIST_DNS}
      - CODE=${EXPRESSVPN_CODE}
      - SERVER=${EXPRESSVPN_SERVER}
      - NETWORK=${EXPRESSVPN_NETWORK}
      - PROTOCOL=${EXPRESSVPN_PROTOCOL}
      - CIPHER=${EXPRESSVPN_CIPHER}
      - BEARER=${EXPRESSVPN_BEARER}
      - IP=${EXPRESSVPN_IP}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 8.8.8.8
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 300M
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    network_mode: service:expressvpn
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${FLARESOLVERR_LOG_LEVEL}
      - LOG_HTML=${FLARESOLVERR_LOG_HTML}
      - CAPTCHA_SOLVER=${FLARESOLVERR_CAPTCHA_SOLVER}
      - TZ=${TZ}
    depends_on:
      expressvpn:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 350M
    healthcheck:
      test: curl --fail -s http://localhost:8191/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  prowlarr:
    image: linuxserver/prowlarr:latest
    network_mode: service:expressvpn
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/prowlarr/config:/config
    restart: unless-stopped
    depends_on:
      expressvpn:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:9696/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 250M
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:arm64v8-latest
    restart: unless-stopped
    network_mode: service:expressvpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/sonarr/config:/config
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/media/tv:/tv
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/DOCKER/transmission/downloads:/downloads
    depends_on:
      prowlarr:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8989/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 250M
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: service:expressvpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/radarr/config:/config
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/media/movies:/movies
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/DOCKER/transmission/downloads:/downloads
    depends_on:
      prowlarr:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:7878/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 250M
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network_mode: service:expressvpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/readarr/config:/config
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/media/books:/books
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/DOCKER/transmission/downloads:/downloads
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    depends_on:
      prowlarr:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8787/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 250M
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    network_mode: service:expressvpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /docker/transmission/config:/config
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/DOCKER/transmission/downloads:/downloads
      - /srv/dev-disk-by-uuid-D6E6E4A3E6E484D9/DOCKER/transmission/watch:/watch
    restart: unless-stopped
    depends_on:
      expressvpn:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:9091/transmission/web/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 250M
    labels:
      com.centurylinklabs.watchtower.enable: "true"
networks: {}
